
name: maybe-crash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: [3.6]
        python-arch: [x64]
        mypy-version: ['0.800', '0.790', '0.782', '0.781', '0.780', '0.770', '0.761', '0.760', '0.750', '0.740']

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install mypy==${{ matrix.mypy-version }}

    - name: Maybe Crash
      run: |
        python crash.py
