
name: self-compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
        python-arch: [x64]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}-${{ matrix.python-arch }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        git clone --branch v0.812 --depth 1 https://github.com/python/mypy.git
        cd mypy
        git submodule update --init mypy/typeshed
        python setup.py develop
        cd ..
        
    - name: Compile Mypy
      env: 
        MYPY_USE_MYPYC: 1
      run: |
        cd mypy
        python setup.py clean install
        cd ..

    - name: No Crash
      run: |
        python crash.py
